### ISSUE TITLE
using json import with relative path or load path doesn't work

### ISSUE THREAD

**Issue by TychosDrunkElk** [vigetlabs/sass-json-vars#13]
I seem to only be able to import json from the root directory, using a json file from a specified load path or with a relative path results in a 'file not found or import unreadable error'. 

```
@import './some/other/directory/var.json';
```

or

```
@import 'var.json';

> sass styles.scss -r sass-json-vars -I some/other/directory
```

**Comment by esr360** [comment]
@TychosDrunkElk  what was the fix for this?
