### ISSUE TITLE
Trouble incorperating sass-json-vars with compass

### ISSUE THREAD

**Issue by mooror** [vigetlabs/sass-json-vars#15]
Hey everyone I am a dev pretty new to sass and compass, but I cannot for the life of me be able to get this module of yours to work with compass. I have tried to add this line of code to my config.rb file:
`gem 'sass-json-vars' ` But it had no effect and I still get this error when I am trying to compile my sass:
`error scss/custom.scss (Line 7: File to import not found or unreadable: jsonfile.json` yet I have made sure my json file is in the same scss folder as everything else. Any help will be great.

P.S. is there any way you guys could add support for compass? That way I can just use a standerd 'require' statment in my config.rb file.

**Comment by mooror** [comment]
Thanks for getting back to me nhunzaker. I will try that out tomorrow afternoon. Sorry for the late reply. I have just had allot of work as of late. Cheers

**Comment by mooror** [comment]
I finally got to trying out your suggestion today. It worked very well and so I am glad to say that I am now closing this issue.I think that perhaps I had some error in my .json as well because only after changing the json to that of the example code was I able to get it to work. But either way it works and I am pleased. Cheers

**Comment by nhunzaker** [comment]
Great to hear!
