### ISSUE TITLE
Libsass compatibility

### ISSUE THREAD

**Issue by cibulka** [vigetlabs/sass-json-vars#20]
Hello! This gem sounds awesome - responsive images and srcset media queries anyone? - so I would love to incorporate it in my workflow.

I have to use Libsass (powered by [grunt-sass](https://github.com/sindresorhus/grunt-sass) with Libsass 3.0.0-) however. Is there any possibility how to make it work with that?

**Comment by pmowrer** [comment]
@cibulka `grunt-sass` is powered by `node-sass`, an implementation of `libsass`. `node-sass` doesn't support (and perhaps never will) requiring gems like this module. I faced the same problem and converted this module into a `node-sass`-compatible module: https://github.com/Updater/node-sass-json-importer

**Comment by nhunzaker** [comment]
@pmowrer Very cool! We'll link to you in the readme.

**Comment by nhunzaker** [comment]
Updated. Thanks, pmowrer!
